-- =============================================================
-- Inicialización de la base de datos all_jokes
-- Este archivo se ejecuta automáticamente cuando el contenedor
-- de PostgreSQL arranca por primera vez (carpeta /docker-entrypoint-initdb.d/)
-- =============================================================

CREATE TABLE IF NOT EXISTS jokes (
  id       SERIAL PRIMARY KEY,
  jokeText TEXT NOT NULL,
  jokeType VARCHAR(50) NOT NULL
);

-- Tabla de usuarios para autenticación JWT
CREATE TABLE IF NOT EXISTS users (
  id            SERIAL PRIMARY KEY,
  username      VARCHAR(50)  UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- Insertar las 100 bromas del dataset original
INSERT INTO jokes (jokeText, jokeType) VALUES
  ('Why don''t scientists trust atoms? Because they make up everything.', 'Science'),
  ('Why did the scarecrow win an award? Because he was outstanding in his field.', 'Puns'),
  ('I told my wife she was drawing her eyebrows too high. She looked surprised.', 'Puns'),
  ('What did one ocean say to the other ocean? Nothing, they just waved.', 'Wordplay'),
  ('Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears.', 'Wordplay'),
  ('How do you organize a space party? You planet!', 'Science'),
  ('Why don''t some couples go to the gym? Because some relationships don''t work out.', 'Puns'),
  ('Parallel lines have so much in common. It''s a shame they''ll never meet.', 'Math'),
  ('What do you call fake spaghetti? An impasta!', 'Food'),
  ('Why did the tomato turn red? Because it saw the salad dressing!', 'Food'),
  ('What do you get when you cross a snowman and a vampire? Frostbite!', 'Wordplay'),
  ('Why did the golfer bring two pairs of pants? In case he got a hole in one!', 'Sports'),
  ('Why are ghosts bad at lying? Because you can see right through them!', 'Wordplay'),
  ('Why can''t you give Elsa a balloon? Because she will let it go.', 'Movies'),
  ('I''m reading a book about anti-gravity. It''s impossible to put down!', 'Science'),
  ('I told my wife she was drawing her eyebrows too high. She looked surprised.', 'Puns'),
  ('What did one ocean say to the other ocean? Nothing, they just waved.', 'Wordplay'),
  ('Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears.', 'Wordplay'),
  ('How do you organize a space party? You planet!', 'Science'),
  ('Why don''t some couples go to the gym? Because some relationships don''t work out.', 'Puns'),
  ('Why was the math teacher suspicious of the graph? Because it had too many shady points.', 'Math'),
  ('What do you call fake spaghetti? An impasta!', 'Food'),
  ('Why did the tomato turn red? Because it saw the salad dressing!', 'Food'),
  ('What do you get when you cross a snowman and a vampire? Frostbite!', 'Wordplay'),
  ('Why did the golfer bring two pairs of pants? In case he got a hole in one!', 'Sports'),
  ('Why are ghosts bad at lying? Because you can see right through them!', 'Wordplay'),
  ('Why can''t you give Elsa a balloon? Because she will let it go.', 'Movies'),
  ('I''m reading a book about anti-gravity. It''s impossible to put down!', 'Science'),
  ('I told my wife she was drawing her eyebrows too high. She looked surprised.', 'Puns'),
  ('What did one ocean say to the other ocean? Nothing, they just waved.', 'Wordplay'),
  ('Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears.', 'Wordplay'),
  ('How do you organize a space party? You planet!', 'Science'),
  ('Why don''t some couples go to the gym? Because some relationships don''t work out.', 'Puns'),
  ('Why did the student do multiplication on the floor? Because the teacher told him not to use tables.', 'Math'),
  ('What do you call fake spaghetti? An impasta!', 'Food'),
  ('Why did the tomato turn red? Because it saw the salad dressing!', 'Food'),
  ('What do you get when you cross a snowman and a vampire? Frostbite!', 'Wordplay'),
  ('Why did the golfer bring two pairs of pants? In case he got a hole in one!', 'Sports'),
  ('Why are ghosts bad at lying? Because you can see right through them!', 'Wordplay'),
  ('Why can''t you give Elsa a balloon? Because she will let it go.', 'Movies'),
  ('I''m reading a book about anti-gravity. It''s impossible to put down!', 'Science'),
  ('I told my wife she was drawing her eyebrows too high. She looked surprised.', 'Puns'),
  ('What did one ocean say to the other ocean? Nothing, they just waved.', 'Wordplay'),
  ('Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears.', 'Wordplay'),
  ('How do you organize a space party? You planet!', 'Science'),
  ('Why don''t some couples go to the gym? Because some relationships don''t work out.', 'Puns'),
  ('Why was the fraction nervous about getting married?', 'Math'),
  ('What do you call fake spaghetti? An impasta!', 'Food'),
  ('Why did the tomato turn red? Because it saw the salad dressing!', 'Food'),
  ('What do you get when you cross a snowman and a vampire? Frostbite!', 'Wordplay'),
  ('Why did the golfer bring two pairs of pants? In case he got a hole in one!', 'Sports'),
  ('Why are ghosts bad at lying? Because you can see right through them!', 'Wordplay'),
  ('Why can''t you give Elsa a balloon? Because she will let it go.', 'Movies'),
  ('I''m reading a book about anti-gravity. It''s impossible to put down!', 'Science'),
  ('I told my wife she was drawing her eyebrows too high. She looked surprised.', 'Puns'),
  ('What did one ocean say to the other ocean? Nothing, they just waved.', 'Wordplay'),
  ('Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears.', 'Wordplay'),
  ('How do you organize a space party? You planet!', 'Science'),
  ('Why don''t some couples go to the gym? Because some relationships don''t work out.', 'Puns'),
  ('Why did the two fours skip lunch? Because they already eight.', 'Math'),
  ('What do you call fake spaghetti? An impasta!', 'Food'),
  ('Why did the tomato turn red? Because it saw the salad dressing!', 'Food'),
  ('What do you get when you cross a snowman and a vampire? Frostbite!', 'Wordplay'),
  ('Why did the golfer bring two pairs of pants? In case he got a hole in one!', 'Sports'),
  ('Why are ghosts bad at lying? Because you can see right through them!', 'Wordplay'),
  ('Why can''t you give Elsa a balloon? Because she will let it go.', 'Movies'),
  ('I''m reading a book about anti-gravity. It''s impossible to put down!', 'Science'),
  ('I told my wife she was drawing her eyebrows too high. She looked surprised.', 'Puns'),
  ('What did one ocean say to the other ocean? Nothing, they just waved.', 'Wordplay'),
  ('Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears.', 'Wordplay'),
  ('How do you organize a space party? You planet!', 'Science'),
  ('Why don''t some couples go to the gym? Because some relationships don''t work out.', 'Puns'),
  ('Why was the obtuse angle always upset? Because it was never right.', 'Math'),
  ('What do you call fake spaghetti? An impasta!', 'Food'),
  ('Why did the tomato turn red? Because it saw the salad dressing!', 'Food'),
  ('What do you get when you cross a snowman and a vampire? Frostbite!', 'Wordplay'),
  ('Why did the golfer bring two pairs of pants? In case he got a hole in one!', 'Sports'),
  ('Why are ghosts bad at lying? Because you can see right through them!', 'Wordplay'),
  ('Why can''t you give Elsa a balloon? Because she will let it go.', 'Movies'),
  ('I''m reading a book about anti-gravity. It''s impossible to put down!', 'Science'),
  ('I told my wife she was drawing her eyebrows too high. She looked surprised.', 'Puns'),
  ('What did one ocean say to the other ocean? Nothing, they just waved.', 'Wordplay'),
  ('Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears.', 'Wordplay'),
  ('How do you organize a space party? You planet!', 'Science'),
  ('Why don''t some couples go to the gym? Because some relationships don''t work out.', 'Puns'),
  ('Why did the math book look so sad? Because it had too many problems.', 'Math'),
  ('What do you call fake spaghetti? An impasta!', 'Food'),
  ('Why did the tomato turn red? Because it saw the salad dressing!', 'Food'),
  ('What do you get when you cross a snowman and a vampire? Frostbite!', 'Wordplay'),
  ('Why did the golfer bring two pairs of pants? In case he got a hole in one!', 'Sports'),
  ('Why are ghosts bad at lying? Because you can see right through them!', 'Wordplay'),
  ('Why can''t you give Elsa a balloon? Because she will let it go.', 'Movies'),
  ('I''m reading a book about anti-gravity. It''s impossible to put down!', 'Science'),
  ('I told my wife she was drawing her eyebrows too high. She looked surprised.', 'Puns'),
  ('What did one ocean say to the other ocean? Nothing, they just waved.', 'Wordplay'),
  ('Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears.', 'Wordplay'),
  ('How do you organize a space party? You planet!', 'Science'),
  ('Why don''t some couples go to the gym? Because some relationships don''t work out.', 'Puns'),
  ('Why was the equal sign so humble? Because it knew it wasn''t less than or greater than anyone else.', 'Math'),
  ('What do you call fake spaghetti? An impasta!', 'Food');
